### ISSUE TITLE
SonarQube version 8.2 support

### ISSUE THREAD

**Issue by lsteck** [Hygieia/hygieia-starter-kit#8]
I'm trying to use the starter kit with SonarQube v8.2 and I'm getting the following error.

`2020-03-18 19:21:19,967 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2020-03-18 19:21:19,977 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-03-18 19:21:19,978 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - http://192.168.0.32:9000
2020-03-18 19:21:19,978 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-03-18 19:21:20,713 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Fetched projects   1             0s
2020-03-18 19:21:20,720 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at com.capitalone.dashboard.model.SonarProject.equals(SonarProject.java:38) ~[sonar-codequality-collector.jar!/:3.1.0]
	at java.util.ArrayList.indexOf(ArrayList.java:321) ~[na:1.8.0_212]
	at java.util.ArrayList.contains(ArrayList.java:304) ~[na:1.8.0_212]
	at com.capitalone.dashboard.collector.SonarCollectorTask.addNewProjects(SonarCollectorTask.java:266) ~[sonar-codequality-collector.jar!/:3.1.0]
	at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:110) ~[sonar-codequality-collector.jar!/:3.1.0]
	at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:37) ~[sonar-codequality-collector.jar!/:3.1.0]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.1.2.jar!/:3.1.0]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
`

**Using Sonar Qube v 6.7 it works fine**

`2020-03-18 19:29:40,000 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2020-03-18 19:29:40,010 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-03-18 19:29:40,010 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - http://192.168.0.32:9000
2020-03-18 19:29:40,011 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-03-18 19:29:40,240 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Fetched projects   1             0s
2020-03-18 19:29:40,241 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New projects            0        0s
2020-03-18 19:29:40,244 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2020-03-18 19:29:40,371 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s
`

**Here is my sonar properties in the docker-compose.yml**

     - SONAR_CRON=0/10 * * * * *
      - SONAR_HOST=http://192.168.0.32:9000
      - SONAR_VERSION=8.2
      - SONAR_METRICS=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details
      - SONAR_USERNAME=admin
      - SONAR_PASSWORD=admin

**Comment by rvema** [comment]
@Sbrenthughes any thoughts?
